import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/providers";
import Header from "../../src/app/components/Header/page"
import Footer from "../../src/app/components/Footer/page"

const inter = Inter({subsets : ["latin"]})
export const metadata: Metadata = {
  title: "👩🏽‍💻 Noella Noronha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning>
      
      <body  className={inter.className}>
        <Providers>
        <Header />
        <main>{children}</main>
        <Footer />
        </Providers>

      </body>
      
    </html>
    
  );
}
